name: CI

on:
  push:
  pull_request:

env:
  RUSTDOCFLAGS: -Dwarnings

jobs:
  check-msrv:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows
          - name: Windows x86_64
            os: windows-2022

          # MacOS
          - name: MacOS x86_64
            os: macos-12

          # Linux
          - name: Linux x86_64
            os: ubuntu-22.04

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
            submodules: true

      - name: caching
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}

      - name: fmt
        shell: bash
        run: cargo fmt --check

      - name: clippy
        shell: bash
        run: cargo clippy -- -D warnings

      - name: test
        shell: bash
        run: cargo test

      - name: doc
        shell: bash
        run: cargo doc


